version: '3.9'

services:
  db:
    image: postgres:16.2-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - mynetwork
    ports:
      - 5433:5432

  app:
    image: app:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    env_file:
      - ./config/.env
    ports:
      - 8080:8080
    networks:
      - mynetwork
    
volumes:
  pgdata:

networks:
  mynetwork: