openapi: '3.0.2'
info:
  title: film-library
  version: '1.0'
servers:
  - url: https://localhost:8080/

security:
  - cookieAuth: []

paths:
  /actors:
    get:
      summary: get actors list
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getActorsResponse"
        '401':
          description: Unauthorized
    post:
      summary: add actor
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/actorInfo"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/actor"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /actors/{id}:
    get:
      summary: get specific actor
      parameters:
        - $ref: "#/components/parameters/actorId"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/actor"
        '401':
          description: Unauthorized
        '404':
          description: Not Found
    put:
      summary: update info about specific actor
      parameters:
        - $ref: "#/components/parameters/actorId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/actorInfo"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/actor"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      summary: delete specific actor
      parameters:
        - $ref: "#/components/parameters/actorId"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/actor"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /films:
    get:
      summary: get films list
      parameters:
        - $ref: "#/components/parameters/filmSort"
        - $ref: "#/components/parameters/actorFilter"
        - $ref: "#/components/parameters/filmFilter"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getFilmsResponse"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"
        '401':
          description: Unauthorized
    post:
      summary: add film
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createFilmRequest"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/film"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /films/{id}:
    get:
      summary: get specific film
      parameters:
        - $ref: "#/components/parameters/filmId"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/film"
        '401':
          description: Unauthorized
        '404':
          description: Not Found
    put:
      summary: update info about specific film
      parameters:
        - $ref: "#/components/parameters/filmId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/filmInfo"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/film"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      summary: delte specific film
      parameters:
        - $ref: "#/components/parameters/filmId"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/film"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /signup:
    post:
      summary: sign up
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/userInfo"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/id"
                  username:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"
      security: []
  /signin:
    post:
      summary: sign in
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/userInfo"
      responses:
        '200':
          description: OK
          headers:
            Set-Cookie:
              schema:
                type: string
                example: jwt=...; Path=/; HttpOnly
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"
      security: []
  

components:
  schemas:
    errorMessage:
      type: object
      properties:
        errorType:
          type: string
          enum: [Validation, Conflict]
        body:
          type: string
    getActorsResponse:
      type: array
      items:
        $ref: "#/components/schemas/actor"
    getFilmsResponse:
      type: array
      items:
        $ref: "#/components/schemas/film"
    createFilmRequest:
      type: object
      properties:
        info:
          $ref: "#/components/schemas/filmInfo"
        actors:
          type: array
          items:
            $ref: "#/components/schemas/id"
    actor:
      type: object
      properties:
        id:
          type: integer
          format: int32
        info:
          $ref: "#/components/schemas/actorInfo"
        films:
          type: array
          items:
            type: string
    film:
      type: object
      properties:
        id:
          type: integer
          format: int32
        info:
          $ref: "#/components/schemas/filmInfo"
        actors:
          type: array
          items:
            type: string
    actorInfo:
      type: object
      properties:
        name:
          type: string
        sex:
          type: string
          enum: ["male", "female"]
        birthday:
          type: string
          format: date
    filmInfo:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 150
        description:
          type: string
          maxLength: 1000
        releasedate:
          type: string
          format: date
        rating:
          type: integer
          minimum: 0
          maximum: 10
    userInfo:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          format: password
    id:
      description: identificator
      type: integer
      format: int32
  parameters:
    actorId:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: int32
      description: The actor id
    filmId:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: int32
      description: The actor id
    filmSort:
      name: sort
      in: query
      schema:
        type: string
        pattern: '^(name|rating|releasedate) (asc|desc)$'
        example: name asc
    actorFilter:
      name: actor
      in: query
      schema:
        type: string
      description: filter by actors matching given keyword
    filmFilter:
      name: film
      in: query
      schema:
        type: string
      description: filter by films matching given keyword
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: jwt
    